# -- Redirects within the same release  -------------------------------------------------

# Important: the redirect is relative to the old path

redirectSameRelease = {
  '4.7': {
    '/cloud-service/cold-storage/index.html':
      '/cloud-service/archive-data/index.html',
    '/cloud-service/cold-storage/access.html':
      '/cloud-service/archive-data/access.html',
    '/cloud-service/cold-storage/configuration.html':
      '/cloud-service/archive-data/configuration.html',
    '/cloud-service/cold-storage/filename-format.html':
      '/cloud-service/archive-data/filename-format.html',
    '/cloud-service/getting-started/register-agents.html':
      '/cloud-service/getting-started/enroll-agents.html',
  },
  '4.6': {
    '/cloud-security/azure/activity-services/active-directory/index.html':
      '/cloud-security/azure/activity-services/entra/index.html',
    '/cloud-security/azure/activity-services/active-directory/graph.html':
      '/cloud-security/azure/activity-services/entra/graph.html',
    '/user-manual/user-administration/single-sign-on/administrator/azure-active-directory.html':
      '/user-manual/user-administration/single-sign-on/administrator/microsoft-entra-id.html',
    '/user-manual/user-administration/single-sign-on/read-only/azure-active-directory.html':
      '/user-manual/user-administration/single-sign-on/read-only/microsoft-entra-id.html',
  },
  '4.4': {
    '/nist/index.html':
      '/compliance/nist/index.html',
    '/nist/visualization-and-dashboard.html':
      '/compliance/nist/visualization-and-dashboard.html',
    '/nist/log-data-analysis.html':
      '/compliance/nist/log-data-analysis.html',
    '/nist/configuration-assessment.html':
      '/compliance/nist/configuration-assessment.html',
    '/nist/malware-detection.html':
      '/compliance/nist/malware-detection.html',
    '/nist/file-integrity-monitoring.html':
      '/compliance/nist/file-integrity-monitoring.html',
    '/nist/system-inventory.html':
      '/compliance/nist/system-inventory.html',
    '/nist/vulnerability-detection.html':
      '/compliance/nist/vulnerability-detection.html',
    '/nist/active-response.html':
      '/compliance/nist/active-response.html',
    '/nist/threat-intelligence.html':
      '/compliance/nist/threat-intelligence.html',
    '/user-manual/capabilities/wazuh-archives.html':
      '/user-manual/manager/wazuh-archives.html',
    '/amazon/services/supported-services/elastic-load-balancing/index.html':
      '/cloud-security/amazon/services/supported-services/elastic-load-balancing/index.html',
    '/amazon/services/supported-services/elastic-load-balancing/alb.html':
      '/cloud-security/amazon/services/supported-services/elastic-load-balancing/alb.html',
    '/amazon/services/supported-services/elastic-load-balancing/nlb.html':
      '/cloud-security/amazon/services/supported-services/elastic-load-balancing/nlb.html',
    '/amazon/services/supported-services/elastic-load-balancing/clb.html':
      '/cloud-security/amazon/services/supported-services/elastic-load-balancing/clb.html',
    '/azure/activity-services/prerequisites/dependencies.html':
      '/cloud-security/azure/activity-services/prerequisites/dependencies.html',
  },
  '4.3': {
   '/user-manual/wazuh-dashboard/single-sign-on/index.html':
     '/user-manual/user-administration/single-sign-on/index.html',
   '/user-manual/wazuh-dashboard/single-sign-on/okta.html':
     '/user-manual/user-administration/single-sign-on/administrator/okta.html',
   '/user-manual/wazuh-dashboard/single-sign-on/azure-active-directory.html':
     '/user-manual/user-administration/single-sign-on/administrator/azure-active-directory.html',
   '/user-manual/wazuh-dashboard/single-sign-on/pingone.html':
     '/user-manual/user-administration/single-sign-on/administrator/pingone.html',
   '/user-manual/wazuh-dashboard/single-sign-on/google.html':
     '/user-manual/user-administration/single-sign-on/administrator/google.html',
   '/user-manual/wazuh-dashboard/single-sign-on/jumpcloud.html':
     '/user-manual/user-administration/single-sign-on/administrator/jumpcloud.html',
   '/user-manual/wazuh-dashboard/single-sign-on/onelogin.html':
     '/user-manual/user-administration/single-sign-on/administrator/onelogin.html',
   '/user-manual/user-administration/single-sign-on/okta.html':
     '/user-manual/user-administration/single-sign-on/administrator/okta.html',
   '/user-manual/user-administration/single-sign-on/azure-active-directory.html':
     '/user-manual/user-administration/single-sign-on/administrator/azure-active-directory.html',
   '/user-manual/user-administration/single-sign-on/pingone.html':
     '/user-manual/user-administration/single-sign-on/administrator/pingone.html',
   '/user-manual/user-administration/single-sign-on/google.html':
     '/user-manual/user-administration/single-sign-on/administrator/google.html',
   '/user-manual/user-administration/single-sign-on/jumpcloud.html':
     '/user-manual/user-administration/single-sign-on/administrator/jumpcloud.html',
   '/user-manual/user-administration/single-sign-on/onelogin.html':
     '/user-manual/user-administration/single-sign-on/administrator/onelogin.html',
   '/user-manual/user-administration/single-sign-on/keycloak.html':
     '/user-manual/user-administration/single-sign-on/administrator/keycloak.html',
   '/user-manual/securing-wazuh/index.html':
     '/user-manual/user-administration/password-management.html',
   '/user-manual/securing-wazuh/wazuh-indexer.html':
     '/user-manual/user-administration/password-management.html',
   '/user-manual/securing-wazuh/opendistro.html':
     '/user-manual/user-administration/password-management.html',
   '/user-manual/securing-wazuh/elastic-stack.html':  
     '/user-manual/user-administration/password-management.html',
   '/user-manual/wazuh-dashboard/rbac.html':
     '/user-manual/user-administration/rbac.html', 
   '/learning-wazuh/build-lab/install-wazuh-central-components.html':
     '/proof-of-concept-guide/index.html',
  },
  '4.2': {
    '/release-notes/release_4_2_0.html':
      '/release-notes/release-4-2-0.html',
    '/user-manual/registering/agent-enrollment.html':  
      '/user-manual/agent-enrollment/via-agent-configuration/index.html',
    '/azure/dependencies.html':  
      '/azure/index.html',
  }
}
