openapi: 3.0.0
info:
  title: Simple API
  description: A simple example to demonstrate OpenAPI 3.0
  version: 1.0.0
servers:
  - url: http://api.example.com/v1
paths:
  /items:
    get:
      summary: Returns a list of items
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Item'
components:
  schemas:
    Item:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string