openapi: 3.0.0

components:
  schemas:
    PolicyRequest:
      type: object
      required:
        - policy
      properties:
        policy:
          type: object
          description: The policy definition that includes policy metadata, description, default state, and the states.
          required:
            - description
            - default_state
            - states
          properties:
            description:
              type: string
              description: A human-readable description of the policy
            default_state:
              type: string
              description: The initial state to apply when the policy is first assigned to an index
            states:
              type: array
              description: A list of states that define the lifecycle behavior
              items:
                $ref: '#/components/schemas/PolicyState'
            schema_version:
              type: integer
              description: The schema version number used for internal tracking of policy changes
            last_updated_time:
              type: integer
              format: int64
              description: Timestamp in ms of the last update to the policy. This is typically set automatically and does not need to be included in requests.

    PolicyState:
      type: object
      required:
        - name
        - actions
        - transitions
      properties:
        name:
          type: string
          description: The name of the state
        actions:
          type: array
          description: List of actions like `rollover`, `delete`, `read_only`, etc.
          items:
            type: object
        transitions:
          type: array
          description: List of transitions to other states, optionally based on conditions. (e.g., `min_index_age`).
          items:
            type: object
            properties:
              state_name:
                type: string
              conditions:
                type: object

    PolicyResponse:
      type: object
      properties:
        _id:
          type: string
          description: The unique identifier of the policy.
        _version:
          type: integer
          description: The version number of the policy, incremented on each update.
        _primary_term:
          type: integer
          description: The primary term used for optimistic concurrency control within the Wazuh indexer.
        _seq_no:
          type: integer
          description: The sequence number for internal versioning.  This helps manage updates and conflict resolution.
        policy:
          type: object
          properties:
            policy:
              type: object
              properties:
                policy_id:
                  type: string
                  description: The identifier of the policy.
                description:
                  type: string
                  description: A description of what the policy is for (e.g., "ingesting logs").
                last_updated_time:
                  type: integer
                  format: int64
                  description: Timestamp in ms of the last time the policy was updated.
                schema_version:
                  type: integer
                  description: Schema version of the policy definition.
                error_notification:
                  type: object
                  nullable: true
                  description: Optional field for setting up notifications (e.g., email or webhook) on policy errors.
                default_state:
                  type: string
                  description: The name of the state where the policy begins
                states:
                  type: array
                  description: A list of lifecycle states the index will pass through.
                  items:
                    $ref: '#/components/schemas/PolicyState'
                ism_template:
                  type: object
                  nullable: true
                  description: Defines index templates to which this policy applies

    AddPolicyRequest:
      type: object
      required:
        - policy_id
      properties:
        policy_id:
          type: string
          description: The ID of the Index State Management (ISM) policy to attach to the index.
        rollover_alias:
          type: string
          description: The alias used for rollover operations.
        is_manual:
          type: boolean
          description: Indicates whether the policy is manually managed. When set to `true`, the policy is not automatically removed.
          default: false

    AddPolicyResponse:
      type: object
      properties:
        updated_indices:
          type: integer
          description: The number of indexes that were successfully updated with the ISM policy.
        failures:
          type: boolean
          description: Indicates whether there were any failures while applying the policy. A value of `false` means all operations completed successfully.
        failed_indices:
          type: array
          description: A list of indexes that failed to be updated. If empty, no failures occurred.
          items:
            type: string

  responses:
    PolicyBadRequest:
      description: Response to report a bad request
      content:
        application/json:
          schema:
            $ref: 'spec.yml#/components/schemas/SecurityError'
          examples:
            missingText:
              value:
                error:
                  root_cause:
                    - type: "illegal_argument_exception"
                      reason: "Missing policy ID"
                  type: "illegal_argument_exception"
                  reason: "Missing policy ID"
                status: 400

    PolicyNotFound:
      description: Response to report a request not found
      content:
        application/json:
          schema:
            $ref: 'spec.yml#/components/schemas/SecurityError'
          example:
            error:
              root_cause:
                - type: "status_exception"
                  reason: "Could not find policy=policy_10"
              type: "status_exception"
              reason: "Could not find policy=policy_10"
            status: 404

    VersionConflict:
      description: Response to report a version conflict
      content:
        application/json:
          schema:
            type: object
            properties:
              error:
                type: object
                properties:
                  root_cause:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                        reason:
                          type: string
                        index:
                          type: string
                        shard:
                          type: integer
                        index_uuid:
                          type: string
                  type:
                    type: string
                  reason:
                    type: string
                  index:
                    type: string
                  shard:
                    type: integer
                  index_uuid:
                    type: string
              status:
                type: integer
          example:
            error:
              root_cause:
                - type: "version_conflict_engine_exception"
                  reason: "[policy_1]: version conflict, document already exists (current version [1])"
                  index: ".opendistro-ism-config"
                  shard: "0"
                  index_uuid: "Bcf6j1bkSKG5-sKZnV11sg"
              type: "version_conflict_engine_exception"
              reason: "[policy_1]: version conflict, document already exists (current version [1])"
              index: ".opendistro-ism-config"
              shard: "0"
              index_uuid: "Bcf6j1bkSKG5-sKZnV11sg"
            status: 409
